import type { Metadata } from "next";
import "./globals.css";
import { Space_Mono } from "@next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const spaceMono = Space_Mono({
    subsets: ["latin"], // choose subset as per need
    weight: ["400", "700"], // use an array to specify multiple weights
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${spaceMono.className} bg-[#DEE6ED]`}>
                {children}
            </body>
        </html>
    );
}
